name: fancy_stream
description: A sophisticated way to use streams, make it even easier to use.
homepage: https://github.com/rcorbellini/FancyStreams

version: 1.2.1+5

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  rxdart: ^0.24.1
  flutter_simple_dependency_injection:
   git:
     url: https://github.com/rcorbellini/flutter_simple_dependency_injection.git



dev_dependencies:
  test: ^1.3.4