name: fancy_stream
description: A sophisticated way to use streams, make it even easier to use.
homepage: https://github.com/rcorbellini/FancyStreams

version: 3.0.0+11

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  rxdart: ^0.26.0
  flutter_simple_dependency_injection: ^1.0.4


dev_dependencies:
  test: ">=1.16.0 <2.0.0"