name: fancy_stream
description: A sophisticated way to use streams, make it even easier to use, highly recommended for use in Bloc Pattern, as it contains functions for easy use of stream / sink dispatch / listen to work with streams without boilerplate.
homepage: https://github.com/rcorbellini/FancyStreams

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+3

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  rxdart: ^0.24.1
  flutter_simple_dependency_injection: ^1.0.2+1

dev_dependencies:
  test: ^1.3.4