name: fancy_stream
description: A sophisticated way to use streams, make it even easier to use.
homepage: https://github.com/rcorbellini/FancyStreams

version: 2.0.0+8

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  meta: ^1.2.4
  rxdart: ^0.25.0
  flutter_simple_dependency_injection: ^1.0.4


dev_dependencies:
  test: ">=1.9.0 <2.0.0"