name: fancy_stream
description: A sophisticated way to use streams, make it even easier to use.
homepage: https://github.com/rcorbellini/FancyStreams

version: 4.0.0+14

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  rxdart: ^0.27.1
  get_it: 
    git:
      url: https://github.com/lucasalmeida-egsys/get_it
      ref: v1.0.4


dev_dependencies:
  test: ">=1.16.0 <2.0.0"
